import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PublicNavbar from "../components/shared/PublicNavbar";
import PublicFooter from "../components/shared/PublicFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#e7e7e3] `}
      >
        <div className="px-1 py-2 md:px-10 md:py-6">
          <PublicNavbar />
        </div>
        {
          children
        }
        <div className="px-1 py-2 md:px-10 md:py-6">
          <PublicFooter></PublicFooter>
        </div>
      </body>
    </html>
  );
}
